
(()=>{
const FILTERS=[{id:'none',label:'なし',css:'none'},{id:'soft',label:'ふんわり',css:'brightness(1.08) saturate(.92) contrast(.95)'},{id:'sparkle',label:'きらきら',css:'brightness(1.06) saturate(1.14) contrast(1.02)'},{id:'film',label:'フィルム',css:'sepia(.18) contrast(.96) saturate(.92) brightness(1.02)'},{id:'sunset',label:'ゆうやけ',css:'sepia(.16) saturate(1.12) brightness(1.04) hue-rotate(-10deg)'},{id:'sky',label:'そらいろ',css:'brightness(1.05) saturate(.92) hue-rotate(10deg)'},{id:'milk',label:'ミルク',css:'brightness(1.1) contrast(.86) saturate(.88)'},{id:'clear',label:'はっきり',css:'brightness(1.04) contrast(1.08) saturate(1.03)'}];
const PASTELS=['#F9B7D1','#FFC6A8','#FFD96A','#FFF3B4','#D6F5B0','#B7F0D0','#BDEBFF','#BFCBFF','#DCC8FF','#F4C8FF','#FFFFFF','#F4EEE7'];
const STICKERS=['💗','✨','🎀','🌼','☁️','🍓','🫧','⭐','🐰','🧸','🌙','💌'];
const $=id=>document.getElementById(id);
const els={video:$('video'),previewImage:$('previewImage'),overlayLayer:$('overlayLayer'),scratchCanvas:$('scratchCanvas'),scratchLabel:$('scratchLabel'),placeholder:$('placeholder'),stage:$('stage'),modeBtns:[...document.querySelectorAll('[data-mode]')],tabBtns:[...document.querySelectorAll('[data-tab]')],titleInput:$('titleInput'),cameraBtn:$('cameraBtn'),pickBtn:$('pickBtn'),saveImageBtn:$('saveImageBtn'),openDataBtn:$('openDataBtn'),saveDataBtn:$('saveDataBtn'),shareDataBtn:$('shareDataBtn'),resetBtn:$('resetBtn'),cameraInput:$('cameraInput'),imageInput:$('imageInput'),dataInput:$('dataInput'),msgError:$('msgError'),msgInfo:$('msgInfo'),textDraft:$('textDraft'),textSize:$('textSize'),textMotion:$('textMotion'),colorChips:$('colorChips'),addTextBtn:$('addTextBtn'),stickerChips:$('stickerChips'),addStickerBtn:$('addStickerBtn'),filterChips:$('filterChips'),selectedEmpty:$('selectedEmpty'),selectedEditor:$('selectedEditor'),selectedSize:$('selectedSize'),selectedMotion:$('selectedMotion'),selectedTextFields:$('selectedTextFields'),selectedTextValue:$('selectedTextValue'),selectedColorChips:$('selectedColorChips'),deleteSelectedBtn:$('deleteSelectedBtn'),panelActions:$('panel-actions'),panelText:$('panel-text'),panelSticker:$('panel-sticker'),panelSelected:$('panel-selected'),panelOpen:$('panel-open'),resetScratchBtn:$('resetScratchBtn')};
const state={mode:'capture',activeTab:'actions',selectedColor:PASTELS[0],selectedSticker:STICKERS[0],stream:null,capturedImage:'',filterId:'soft',overlays:[],selectedId:null,drag:null,openScene:null};
const DEFAULT_STICKER_SIZE=42;
const DEFAULT_STICKER_MOTION='float';
function uid(){return `${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function clamp(n,min,max){return Math.min(max,Math.max(min,n))}
function nowStamp(){const d=new Date();const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`}
function safeName(t){return (t||'houkago-camera').trim().replace(/[^a-zA-Z0-9ぁ-んァ-ヶ一-龯ー_-]+/g,'-').replace(/^-+|-+$/g,'')||'houkago-camera'}
function dataFileName(){return `${safeName(els.titleInput.value)}-${nowStamp()}.hokago`}
function imageFileName(){return `${safeName(els.titleInput.value)}-${nowStamp()}.png`}
function selectedItem(){return state.overlays.find(x=>x.id===state.selectedId)||null}
function setMessage(text,type='info'){const info=els.msgInfo, err=els.msgError; info.classList.add('hidden'); err.classList.add('hidden'); if(!text)return; (type==='error'?err:info).textContent=text; (type==='error'?err:info).classList.remove('hidden')}
function buildScene(){if(!state.capturedImage)return null;return {version:10,title:els.titleInput.value,imageDataUrl:state.capturedImage,filter:state.filterId,overlays:state.overlays,createdAt:new Date().toISOString()}}
function renderTabs(){const panels={actions:els.panelActions,text:els.panelText,sticker:els.panelSticker,selected:els.panelSelected};Object.entries(panels).forEach(([k,p])=>p.classList.toggle('active',state.activeTab===k));els.tabBtns.forEach(b=>b.classList.toggle('active',b.dataset.tab===state.activeTab))}
function renderModes(){els.modeBtns.forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode))}
function renderButtons(){const on=!!state.capturedImage;[els.saveImageBtn,els.saveDataBtn,els.shareDataBtn,els.addTextBtn,els.addStickerBtn].forEach(b=>b.disabled=!on)}
function renderColorChips(root,current,onSelect){root.innerHTML='';PASTELS.forEach(c=>{const b=document.createElement('button');b.className='colorChip'+(c===current?' active':'');b.style.background=c;b.type='button';b.addEventListener('click',()=>onSelect(c));root.appendChild(b)})}
function renderStickerChips(){els.stickerChips.innerHTML='';STICKERS.forEach(s=>{const b=document.createElement('button');b.className='stickerChip'+(state.selectedSticker===s?' active':'');b.type='button';b.textContent=s;b.style.fontSize='26px';b.addEventListener('click',()=>{state.selectedSticker=s;renderStickerChips()});els.stickerChips.appendChild(b)})}
function renderFilterChips(){els.filterChips.innerHTML='';FILTERS.forEach(f=>{const b=document.createElement('button');b.className='filterChip'+(state.filterId===f.id?' active':'');b.type='button';b.textContent=f.label;b.addEventListener('click',()=>{state.filterId=f.id;renderFilterChips();renderPreview()});els.filterChips.appendChild(b)})}
function renderSelected(){const item=selectedItem();const show=!!item;els.selectedEmpty.classList.toggle('hidden',show);els.selectedEditor.classList.toggle('hidden',!show);if(!item)return;els.selectedSize.min=item.kind==='text'?'18':'26';els.selectedSize.max=item.kind==='text'?'52':'80';els.selectedSize.value=String(item.size);els.selectedMotion.value=item.motion;if(item.kind==='text'){els.selectedTextFields.classList.remove('hidden');els.selectedTextValue.value=item.value;renderColorChips(els.selectedColorChips,item.color,(c)=>{item.color=c;renderPreview();renderSelected()})}else{els.selectedTextFields.classList.add('hidden')}}
function renderOverlayLayer(items,editable){els.overlayLayer.innerHTML='';els.overlayLayer.classList.remove('hidden');items.forEach(item=>{const wrap=document.createElement('div');wrap.className=`overlay ${item.kind} motion-${item.motion}`+(editable&&state.selectedId===item.id?' selected':'');wrap.style.left=`${item.x*100}%`;wrap.style.top=`${item.y*100}%`;wrap.dataset.id=item.id;const span=document.createElement('span');span.textContent=item.value;span.style.fontSize=`${item.size}px`;if(item.kind==='text')span.style.color=item.color;wrap.appendChild(span);if(editable){wrap.addEventListener('pointerdown',(e)=>{e.preventDefault();e.stopPropagation();state.selectedId=item.id;const r=els.stage.getBoundingClientRect();state.drag={id:item.id,startX:e.clientX,startY:e.clientY,baseX:item.x,baseY:item.y,w:r.width,h:r.height};state.activeTab='selected';renderAll()})}else{wrap.style.pointerEvents='none'}els.overlayLayer.appendChild(wrap)})}
function renderPreview(){els.video.classList.add('hidden');els.previewImage.classList.add('hidden');els.overlayLayer.classList.add('hidden');els.scratchCanvas.classList.add('hidden');els.scratchLabel.classList.add('hidden');els.placeholder.classList.add('hidden');els.panelOpen.classList.toggle('hidden',!(state.mode==='open'&&state.openScene));
  if(state.mode==='capture'&&!state.capturedImage){if(state.stream){els.video.classList.remove('hidden')}else{els.placeholder.classList.remove('hidden')}return}
  if(state.mode==='open'){
    if(!state.openScene){els.placeholder.classList.remove('hidden');els.placeholder.textContent='受け取ったデータを選ぶと、ここで削って見られます。';return}
    els.previewImage.src=state.openScene.imageDataUrl;els.previewImage.style.filter=(FILTERS.find(f=>f.id===state.openScene.filter)||FILTERS[0]).css;els.previewImage.classList.remove('hidden');renderOverlayLayer(state.openScene.overlays,false);els.scratchCanvas.classList.remove('hidden');els.scratchLabel.classList.remove('hidden');setTimeout(initScratch,0);return;
  }
  if(state.capturedImage){els.previewImage.src=state.capturedImage;els.previewImage.style.filter=(FILTERS.find(f=>f.id===state.filterId)||FILTERS[0]).css;els.previewImage.classList.remove('hidden');renderOverlayLayer(state.overlays,true);return}
  els.placeholder.classList.remove('hidden')
}
function renderAll(){renderModes();renderTabs();renderButtons();renderSelected();renderPreview()}
async function startVideoCamera(){setMessage(''); if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){setMessage('このブラウザではカメラに対応していません。写真を選ぶを使ってください。','error');return} try{stopVideoCamera(); const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false}); state.stream=s; els.video.srcObject=s; els.video.classList.remove('hidden'); await els.video.play().catch(()=>{}); renderPreview(); }catch(e){setMessage('カメラが使えないため、写真を選んで試せます。','error')}}
function stopVideoCamera(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null;els.video.srcObject=null}}
function openCamera(){ if(window.innerWidth<800){ els.cameraInput.click(); } else { if(state.mode!=='capture'){state.mode='capture'; renderAll();} startVideoCamera(); setMessage('PCではライブ映像が出たら、もう一度「カメラで撮る」を押すと撮影します。'); if(state.stream&&els.video.videoWidth){ captureFromVideo(); } } }
function captureFromVideo(){ if(!els.video.videoWidth){setMessage('カメラの準備ができたら、もう一度押してください。'); return;} const c=document.createElement('canvas'); c.width=els.video.videoWidth; c.height=els.video.videoHeight; const ctx=c.getContext('2d'); ctx.drawImage(els.video,0,0,c.width,c.height); state.capturedImage=c.toDataURL('image/jpeg',.92); stopVideoCamera(); state.mode='decorate'; state.activeTab='text'; renderAll(); }
function readImageFile(file){ const fr=new FileReader(); fr.onload=()=>{state.capturedImage=String(fr.result||''); state.mode='decorate'; state.activeTab='text'; stopVideoCamera(); renderAll();}; fr.readAsDataURL(file); }
function addText(){ if(!state.capturedImage){setMessage('先に写真を入れてください。','error'); return;} const value=els.textDraft.value.trim(); if(!value){setMessage('文字を入力してください。','error'); return;} const item={id:uid(),kind:'text',x:.5,y:.78,size:Number(els.textSize.value),color:state.selectedColor,motion:els.textMotion.value,value}; state.overlays.push(item); state.selectedId=item.id; state.activeTab='selected'; renderAll(); setMessage('文字を追加しました。'); }
function addSticker(){ if(!state.capturedImage){setMessage('先に写真を入れてください。','error'); return;} const item={id:uid(),kind:'sticker',x:.78,y:.2,size:DEFAULT_STICKER_SIZE,motion:DEFAULT_STICKER_MOTION,value:state.selectedSticker}; state.overlays.push(item); state.selectedId=item.id; state.activeTab='selected'; renderAll(); setMessage('スタンプを追加しました。'); }
function deleteSelected(){ if(!state.selectedId)return; state.overlays=state.overlays.filter(x=>x.id!==state.selectedId); state.selectedId=null; renderAll(); }
function resetAll(){ stopVideoCamera(); state.mode='capture'; state.capturedImage=''; state.filterId='soft'; state.overlays=[]; state.selectedId=null; state.openScene=null; els.titleInput.value='放課後カメラ'; state.activeTab='actions'; setMessage(''); renderAll(); }
async function saveImage(){ const scene=buildScene(); if(!scene)return; const img=await new Promise((res,rej)=>{ const i=new Image(); i.onload=()=>res(i); i.onerror=rej; i.src=scene.imageDataUrl; }); const c=document.createElement('canvas'); c.width=img.naturalWidth||1080; c.height=img.naturalHeight||1440; const ctx=c.getContext('2d'); const scale=c.width/320; ctx.filter=(FILTERS.find(f=>f.id===scene.filter)||FILTERS[0]).css; ctx.drawImage(img,0,0,c.width,c.height); ctx.filter='none'; ctx.textAlign='center'; ctx.textBaseline='middle'; for(const item of scene.overlays){ const x=item.x*c.width, y=item.y*c.height, size=item.size*scale; if(item.kind==='text'){ ctx.save(); ctx.font=`700 ${size}px Arial,sans-serif`; ctx.fillStyle=item.color; ctx.shadowColor='rgba(255,255,255,.72)'; ctx.shadowBlur=Math.max(2,size*.08); ctx.fillText(item.value,x,y); ctx.restore(); } else { ctx.save(); ctx.font=`${size}px Arial,sans-serif`; ctx.fillText(item.value,x,y); ctx.restore(); } } const a=document.createElement('a'); a.href=c.toDataURL('image/png'); a.download=imageFileName(); a.click(); setMessage(`画像を保存しました: ${a.download}`); }
function saveData(){ const scene=buildScene(); if(!scene)return; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(scene,null,2)],{type:'application/json'})); a.download=dataFileName(); a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); setMessage(`データを保存しました: ${a.download}`); }
async function shareData(){ const scene=buildScene(); if(!scene)return; const file=new File([JSON.stringify(scene,null,2)],dataFileName(),{type:'application/json'}); try{ if(navigator.canShare&&navigator.canShare({files:[file]})){ await navigator.share({title:scene.title,text:'このアプリで開く写真を送ります',files:[file]}); setMessage('データ送信画面を開きました。'); } else { setMessage('この端末では直接送れないため、先に「データを保存」を使ってください。'); } } catch(e){ setMessage('送信はキャンセルされました。'); } }
function openData(file){ const fr=new FileReader(); fr.onload=()=>{ try{ const data=JSON.parse(String(fr.result||'')); if(!data.imageDataUrl||!Array.isArray(data.overlays)) throw new Error('bad'); state.openScene=data; state.mode='open'; renderAll(); setMessage('受け取ったデータを開きました。'); }catch(e){ setMessage('データを読み込めませんでした。','error'); } }; fr.readAsText(file); }
function initScratch(){ if(!state.openScene)return; const canvas=els.scratchCanvas, rect=canvas.getBoundingClientRect(), dpr=window.devicePixelRatio||1; canvas.width=Math.max(1,Math.round(rect.width*dpr)); canvas.height=Math.max(1,Math.round(rect.height*dpr)); const ctx=canvas.getContext('2d'); ctx.setTransform(1,0,0,1,0,0); ctx.scale(dpr,dpr); ctx.clearRect(0,0,rect.width,rect.height); ctx.fillStyle='#C8C3BC'; ctx.fillRect(0,0,rect.width,rect.height); ctx.fillStyle='rgba(255,255,255,.16)'; for(let i=0;i<7;i++){ctx.beginPath();ctx.arc((rect.width/8)*(i+1),rect.height*.2,rect.width*.08,0,Math.PI*2);ctx.fill();}}
function scratchAt(x,y){ const rect=els.scratchCanvas.getBoundingClientRect(); const ctx=els.scratchCanvas.getContext('2d'); ctx.save(); ctx.globalCompositeOperation='destination-out'; ctx.beginPath(); ctx.arc(x-rect.left,y-rect.top,Math.max(28,rect.width*.06),0,Math.PI*2); ctx.fill(); ctx.restore(); }
renderColorChips(els.colorChips,state.selectedColor,(c)=>{state.selectedColor=c; renderColorChips(els.colorChips,state.selectedColor,arguments.callee)});
function rerenderMainColors(){ renderColorChips(els.colorChips,state.selectedColor,(c)=>{state.selectedColor=c; rerenderMainColors();}); }
rerenderMainColors(); renderStickerChips(); renderFilterChips();
els.modeBtns.forEach(b=>b.addEventListener('click',()=>{ state.mode=b.dataset.mode; if(state.mode==='capture'&&!state.capturedImage) startVideoCamera(); renderAll(); }));
els.tabBtns.forEach(b=>b.addEventListener('click',()=>{ state.activeTab=b.dataset.tab; renderTabs(); }));
els.cameraBtn.addEventListener('click',()=>{ if(window.innerWidth<800){ els.cameraInput.click(); } else { if(state.stream&&els.video.videoWidth) captureFromVideo(); else startVideoCamera(); }});
els.pickBtn.addEventListener('click',()=>els.imageInput.click()); els.openDataBtn.addEventListener('click',()=>els.dataInput.click()); els.saveImageBtn.addEventListener('click',saveImage); els.saveDataBtn.addEventListener('click',saveData); els.shareDataBtn.addEventListener('click',shareData); els.resetBtn.addEventListener('click',resetAll); els.addTextBtn.addEventListener('click',addText); els.addStickerBtn.addEventListener('click',addSticker); els.deleteSelectedBtn.addEventListener('click',deleteSelected); els.resetScratchBtn.addEventListener('click',initScratch);
els.cameraInput.addEventListener('change',e=>{ const f=e.target.files&&e.target.files[0]; if(f) readImageFile(f); e.target.value=''; });
els.imageInput.addEventListener('change',e=>{ const f=e.target.files&&e.target.files[0]; if(f) readImageFile(f); e.target.value=''; });
els.dataInput.addEventListener('change',e=>{ const f=e.target.files&&e.target.files[0]; if(f) openData(f); e.target.value=''; });
els.selectedSize.addEventListener('input',()=>{ const item=selectedItem(); if(!item)return; item.size=Number(els.selectedSize.value); renderPreview(); });
els.selectedMotion.addEventListener('change',()=>{ const item=selectedItem(); if(!item)return; item.motion=els.selectedMotion.value; renderPreview(); });
els.selectedTextValue.addEventListener('input',()=>{ const item=selectedItem(); if(!item||item.kind!=='text')return; item.value=els.selectedTextValue.value; renderPreview(); });
window.addEventListener('pointermove',e=>{ if(!state.drag)return; const item=state.overlays.find(x=>x.id===state.drag.id); if(!item)return; const dx=(e.clientX-state.drag.startX)/state.drag.w; const dy=(e.clientY-state.drag.startY)/state.drag.h; item.x=clamp(state.drag.baseX+dx,.05,.95); item.y=clamp(state.drag.baseY+dy,.05,.95); renderPreview(); renderSelected(); });
window.addEventListener('pointerup',()=>{ state.drag=null; });
els.scratchCanvas.addEventListener('pointerdown',e=>scratchAt(e.clientX,e.clientY)); els.scratchCanvas.addEventListener('pointermove',e=>{ if(e.buttons!==1) return; scratchAt(e.clientX,e.clientY); });
window.addEventListener('resize',()=>{ if(state.mode==='open'&&state.openScene) initScratch(); });
if('serviceWorker' in navigator){ window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=12').catch(()=>{})); }
renderAll(); startVideoCamera();
})();
